services:
  backend:
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - formfio-network

  database:
    image: redis:8.0.3-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis_users.acl:/usr/local/etc/redis/redis_users.acl:ro
    command: [ "redis-server", "--aclfile", "/usr/local/etc/redis/redis_users.acl" ]

  frontend:
    build: ./frontend
    ports:
      - "5173:80"

networks:
  formfio-network:
    enable_ipv6: true